### ISSUE TITLE
ValueError: Invalid value NaN (not a number)

### ISSUE THREAD

**Issue by kleajmp** [rajparmarr2308/InstaReelScrapper#1]
Is this script still working 2022/06 ?

```
Traceback (most recent call last):
  File "RealReelScraper.py", line 15, in <module>
    google_reel.scrape(headers=headers)
  File "C:\Python310\lib\site-packages\instascrape\scrapers\post.py", line 88, in scrape
    return_instance.upload_date = datetime.datetime.fromtimestamp(return_instance.timestamp)
ValueError: Invalid value NaN (not a number)
```

If it has something to do with the int(time.time()) it can not because I also tried without the timestamp and with os.path:
`filepath= os.path.join("Z:","Instascraper",f"reel_{int(time.time())}.mp4")`

Any idea what caused the problem?

**Comment by crawpappy** [comment]
I'm getting this same error. Any fixes?
